### ISSUE TITLE
what is the structure of Secret.dart ?

### ISSUE THREAD

**Issue by LebToki** [Reshav-Paul/grodudes_app#5]
Do you call them this way ?
it's missing from your source 

tried the below
Final consumerKey= "";
Final consumerSecret = "";
but didn't reach anywhere

would appreciate some light

**Comment by Reshav-Paul** [comment]
I dont have the local copy anymore.

Looks like you can just define a map like,
```
final secret = {
    consumerKey: "ck_________"
    consumerSecret: "cs___________"
}
```

**Comment by LebToki** [comment]
final secret = {

  "consumerKey": "ck_____________________________________________",
  "consumerSecret": "cs__________________________________________",
};
