### ISSUE TITLE
help config

### ISSUE THREAD

**Issue by NicadoX** [Reshav-Paul/grodudes_app#7]
how do I set up the app?
I change the woocommerce key but it doesn't work.
could you inform me simple tutorial

**Comment by Reshav-Paul** [comment]
Have you changed the url to point to your site?

My advice would be to check the http response you are getting for the common get requests like getting products and categories. 

Most probably you can get a hint of what's going wrong there.

**Comment by NicadoX** [comment]
Have you changed the url to point to your site? Yes

    url: 'url',
    consumerKey: '*******************************************************',
    consumerSecret: '*******************************************************',

"Failed to load data. Please Check your Internet Connection"

**Comment by Reshav-Paul** [comment]
In main.dart file find the loadData() function. Inside it there is a section where I check if the site is in maintenance mode. Comment out that section or remove it because that was a custom implementation and won't work in your case.

You can find it in the first try...catch block. Remove it and see if it works.

**Comment by NicadoX** [comment]
I tried to remove however it generated this error

error https://pastebin.com/rb1UiKBN

my main.dart https://pastebin.com/g363RuwA

**Comment by Reshav-Paul** [comment]
You have removed the line Function loadData.... along with the try...catch block. That's a syntax error.

**Comment by NicadoX** [comment]
Solved, thank you very much

**Comment by Reshav-Paul** [comment]
Great. Closing this then.
